<?php

namespace Carrito\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UsuarioRepository extends EntityRepository {
	
	
	public function validarUsuario($user,$pass)
	{
		//si uso findBy o findOneBy no uso getEntityManager
// 		return $this->getEntityManager()
		return $this->findOneBy(array("nombre" => $user,"pass" => $pass));
		
		//PARA ENTITY MANAGER
// 		->createQueryBuilder('u')
// 		->where('u.nombre = :nombre and u.pass = :pass')
// 		->setParameter('nombre',$user)
//      	->setParameter('pass',$pass)
//      	->getQuery();
	}
	
}