<?php

namespace Carrito\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UsuarioRepository extends EntityRepository {
	
	
	public function validarUsuario($user,$pass)
	{
		return $this->findOneBy(array("nombre" => $user,"pass" => $pass));
	}
	
}